### ISSUE TITLE
YAML Export Option

### ISSUE THREAD

**Issue by rvare** [rvare/SimpleJotts#4]
It might be possible to make an option to export notes to YAML. This should be allowed for both a single note and all notes.

The proposal for this feature is as follows:

- Export a single note in a single YAML file.
- Export all notes in a single YAML file.
- Use two spaces to indent.
- Use `|` to preserve newlines.
- Use `---` and `...` for each note

The following is an example of what the YAML contents will look like:

```yaml
---
id: 1
date_created: 2025-05-28T13:00:26.466305200
date_modified: 2025-06-05T13:00:26.466305200
content: |
  A note and what not.
...
```
